<html>

    <head>
        <meta charset="utf-8">
        <title>Twitter</title>
        
        <!-- Custom Style CSS -->
        <link rel="stylesheet" type="text/css" href="/css/style.css">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        
        <!-- Kit Icons Font Awesome -->
        <script src="https://kit.fontawesome.com/94fb6d8945.js" crossorigin="anonymous"></script>
    </head>

    <body>
        <?= $this->content() ?>
    </body>

</html>