<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center mt-2">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
              
              <div class="form-group mb-3 mt-3">
                <input type="text" class="form-control" placeholder="Nome" name="nome" value="<?= $this->view->usuario["nome"] ?>">
              </div>
              
              <div class="form-group mb-3">
                <input type="text" class="form-control" placeholder="E-mail" name="email" value="<?= $this->view->usuario["email"] ?>">
              </div>

              <div class="form-group mb-3">
                <input type="password" class="form-control" placeholder="Senha" name="senha" value="<?= $this->view->usuario["senha"] ?>">
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text text-dark">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block w-100">Inscrever-se</button>

              <?php if($this->view->erroCadastro) { ?>
                <div class="mt-3 text-center">
                  <small class="form-text text-danger">*Erro ao tentar realizar o cadastro! <br>Verifique se os campos foram preenchidos corretamente.</small>
                </div>
              <?php } ?>

            </form>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>